#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin
DOC=$PRE/share/doc/jx_layout
APP=$PRE/share/applications
ICON=$PRE/share/pixmaps

mkdir -p $BIN;
install -m755 jx_layout $BIN

mkdir -p $DOC
cp README.md COPYING menu_strings $DOC

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/*.desktop $APP/;
	cp desktop/*.xpm     $ICON/;
fi
