// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_All_Preferences
#define _H_All_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __EditPreferences::All"
"|* %i __EditToolBar::All"
"|* %i __MacWinXEmulation::All %l"
"|* %i __SaveWindowSetupAsDefault::All"
;

enum {
	kPrefsCmd=1,
	kEditToolBarCmd,
	kEditMacWinPrefsCmd,
	kSaveWindSizeCmd,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu) {
	if (JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
};

#endif
