// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RecordDirector_File
#define _H_RecordDirector_File

static const JUtf8Byte* kFileMenuStr =
"* %i OpenFiles::MDRecordDirector %l"
"|* %i __PageSetup::RecordDirector"
"|* %i Print::JX %l"
"|* %i CloseWindow::JX %l"
"|* %i Quit::JX"
;

enum {
	kOpenSelCmd=1,
	kPageSetupCmd,
	kPrintCmd,
	kCloseCmd,
	kQuitCmd,
};

#include <jx-af/image/jx/jx_file_print.xpm>

static void ConfigureFileMenu(JXTextMenu* menu) {
	if (JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
	menu->SetItemImage(kPrintCmd, jx_file_print);
};

#endif
