// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_StatsDirector_File_enum
#define _H_StatsDirector_File_enum

enum {
	kQuitCmd=1,
};

#endif
