#!/bin/sh

rm -f  /usr/X11R6/bin/mondrian;
rm -rf /usr/lib/mondrian;
rm -rf /usr/share/doc/mondrian;
rm -f  `find /usr/share/applications -name 'mondrian*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'mondrian*.xpm'`;
