path_classifiers:
  library:
    - misc
  docs:
    - doc
  test:
    - obsolete

extraction:
  cpp:
     configure:
        command:
        - ./configure release
     index:
        build_command:
        - make
