language: cpp

script:
  - curl -O -L http://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip
  - unzip build-wrapper-macosx-x86.zip
  - ./configure && ./build-wrapper-macosx-x86/build-wrapper-macosx-x86 make test
  - sonar-scanner

matrix:
  include:
    - os: osx
      osx_image: xcode10

  # libace 6.0.3 on Trusty is broken
  exclude:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"

addons:
  sonarcloud:
    organization: "jafl-github"

before_install:
  - eval "${MATRIX_EVAL}"

after_success:
  - bash <(curl -s https://codecov.io/bash) -p libjcore
