language: cpp
script: ./configure && make test
matrix:
  include:
    - os: osx
      osx_image: xcode10

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && TRAVIS_CI_LLDB_VERS=3.9"

before_install:
  - eval "${MATRIX_EVAL}"
