language: cpp
script: ./configure && make test
matrix:
  include:
    - os: osx
      osx_image: xcode10

  # libace 6.0.3 on Trusty is broken
  exclude:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; pyenv install 2.7.6; pyenv global 2.7.6; pyenv rehash; pip install cpp-coveralls; pyenv rehash; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi

after_success:
  - #bash <(curl -s https://codecov.io/bash)
  - coveralls --root libjcore --build-root libjcore --exclude test --gcov-options '\-lp'
