language: cpp

script:
  - ./configure
  - make default test

matrix:
  exclude:
    - os: osx
      osx_image: xcode12.5
  include:
    - os: linux
      dist: focal

before_install:
  - eval "${MATRIX_EVAL}"

after_success:
  - bash <(curl -s https://codecov.io/bash) -p libjcore

cache:
  directories:
    - "misc/reflex"
