language: cpp

addons:
  sonarcloud:
    organization: "jafl-github"

script:
  - ./configure
  - mkdir sonar_output
  - chmod 0777 sonar_output
  - build-wrapper-linux-x86-64 --out-dir sonar_output make default test
  - sonar-scanner

matrix:
  exclude:
    - os: osx
      osx_image: xcode12.5
  include:
    - os: linux
      dist: focal

before_install:
  - eval "${MATRIX_EVAL}"

after_success:
  - bash <(curl -s https://codecov.io/bash) -p libjcore

cache:
  directories:
    - ".sonar/cache"
    - "misc/reflex"
