#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/<Binary>
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

install -m755 <Binary> $BIN

mkdir -p $DOC
cp README.md COPYING menu_strings $DOC

cp desktop/<Binary>.desktop $APP/
cp desktop/<Binary>.xpm     $ICON/
