#!/bin/bash

rm -f  /usr/bin/<Binary>;
rm -rf /usr/lib/<Binary>;
rm -rf /usr/share/doc/<Binary>;
rm -f  `find /usr/share/applications -name '<Binary>*.desktop'`;
rm -f  `find /usr/share/pixmaps -name '<Binary>*.xpm'`;
