#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/<Binary>;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/<Binary>;
rm -rf $DOC;
rm -f  `find $APP -name '<Binary>*.desktop'`;
rm -f  `find $ICON -name '<Binary>*.xpm'`;
