// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXExprEditor_Math
#define _H_JXExprEditor_Math

static const JUtf8Byte* kMathMenuStr =
"* %i __Evaluate::JXExprEditor"
"|* %i __PrintToEPS::JXExprEditor %l"
"|* %i __Negate::JXExprEditor"
"|* %i __ApplyFunction::JXExprEditor %l"
"|* %i __AddArgument::JXExprEditor"
"|* %i __MoveLeft::JXExprEditor"
"|* %i __MoveRight::JXExprEditor %l"
"|* %i __GroupLeft::JXExprEditor"
"|* %i __GroupRight::JXExprEditor"
"|* %i __Ungroup::JXExprEditor"
;

enum {
	kEvaluateItemIndex=1,
	____PrintToEPS,
	____Negate,
	kApplyFnToSelIndex,
	____AddArgument,
	____MoveLeft,
	____MoveRight,
	____GroupLeft,
	____GroupRight,
	____Ungroup,
};


static void ConfigureMathMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#m", JString::kNoCopy));
	}
};

#endif
