// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXExprEditor_Font
#define _H_JXExprEditor_Font

static const JUtf8Byte* kFontMenuStr =
"* %r %i __Normal::JXExprEditor"
"|* %r %i __Greek::JXExprEditor"
;

enum {
	____Normal=1,
	____Greek,
};


static void ConfigureFontMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
};

#endif
