// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXExprEditor_Font
#define _H_JXExprEditor_Font

static const JUtf8Byte* kFontMenuStr =
"* %r %i __Normal::JXExprEditor"
"|* %r %i __Greek::JXExprEditor"
;

#include "JXExprEditor-Font-enum.h"


static void ConfigureFontMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
};

#endif
