// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXExprEditor_Function_enum
#define _H_JXExprEditor_Function_enum

enum {
	____absoluteValue=1,
	____squareRoot,
	____logarithmAnyBase,
	____naturalLogarithm,
	____sine,
	____cosine,
	____tangent,
	____inverseSine,
	____inverseCosine,
	____inverseTangent,
	____inverseTangentYX,
	____hyperbolicSine,
	____hyperbolicCosine,
	____hyperbolicTangent,
	____inverseHyperbolicSine,
	____inverseHyperbolicCosine,
	____inverseHyperbolicTangent,
	____realPart,
	____imaginaryPart,
	____phaseAngle,
	____complexConjugate,
	____rotateZAngle,
	____minimum,
	____maximum,
	____parallel,
	____algebraicSign,
	____roundToInteger,
	____truncateToInteger,
};

#endif
