// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestTextEditDocument_File_enum
#define _H_TestTextEditDocument_File_enum

enum {
	kNewFileCmd=1,
	kOpenFileCmd,
	kSaveFileCmd,
	kSaveFileAsCmd,
	kSaveCopyAsCmd,
	kRevertCmd,
	kReadPrivateFmtCmd,
	kWritePrivateFmtCmd,
	kPageSetupCmd,
	kPrintCmd,
	kCloseCmd,
};

#endif
