// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestTextEditDocument_Emulator
#define _H_TestTextEditDocument_Emulator

static const JUtf8Byte* kEmulatorMenuStr =
"* %r %i __None::TestTextEditDocument"
"|* %r %i __vi::TestTextEditDocument"
;

#include "TestTextEditDocument-Emulator-enum.h"


static void ConfigureEmulatorMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#e");
	}
};

#endif
