// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestTextEditDocument_File
#define _H_TestTextEditDocument_File

static const JUtf8Byte* kFileMenuStr =
"* %i __New::TestTextEditDocument"
"|* %i __Open::TestTextEditDocument"
"|* %i __Save::TestTextEditDocument"
"|* %i __SaveAs::TestTextEditDocument"
"|* %i __SaveACopyAs::TestTextEditDocument"
"|* %i __RevertToSaved::TestTextEditDocument %l"
"|* %i __LoadPrivateFormat::TestTextEditDocument"
"|* %i __SavePrivateFormat::TestTextEditDocument %l"
"|* %i __PageSetup::TestTextEditDocument"
"|* %i __Print::TestTextEditDocument %l"
"|* %i __Close::TestTextEditDocument"
;

enum {
	kNewFileCmd=1,
	kOpenFileCmd,
	kSaveFileCmd,
	kSaveFileAsCmd,
	kSaveCopyAsCmd,
	kRevertCmd,
	kReadPrivateFmtCmd,
	kWritePrivateFmtCmd,
	kPageSetupCmd,
	kPrintCmd,
	kCloseCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_new
#define _H_jx_af_image_jx_jx_file_new
#include <jx-af/image/jx/jx_file_new.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_save
#define _H_jx_af_image_jx_jx_file_save
#include <jx-af/image/jx/jx_file_save.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_revert_to_saved
#define _H_jx_af_image_jx_jx_file_revert_to_saved
#include <jx-af/image/jx/jx_file_revert_to_saved.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
	menu->SetItemImage(kNewFileCmd + offset, jx_file_new);
	menu->SetItemImage(kOpenFileCmd + offset, jx_file_open);
	menu->SetItemImage(kSaveFileCmd + offset, jx_file_save);
	menu->SetItemImage(kRevertCmd + offset, jx_file_revert_to_saved);
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
