// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestImageDirector_File_enum
#define _H_TestImageDirector_File_enum

enum {
	kOpenImageCmd=1,
	kSaveGIFCmd,
	kSavePNGCmd,
	kSaveJPEGCmd,
	kSaveXPMCmd,
	kSaveMaskXBMCmd,
	kCopyImageCmd,
	kPasteImageCmd,
	kPageSetupCmd,
	kPrintPSCmd,
	kPrintEPSCmd,
	kCloseCmd,
};

#endif
