// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestStringTable_BorderWidth
#define _H_TestStringTable_BorderWidth

static const JUtf8Byte* kBorderWidthMenuStr =
"* %r %i __0::TestStringTable"
"|* %r %i __1::TestStringTable"
"|* %r %i __2::TestStringTable"
"|* %r %i __3::TestStringTable"
"|* %r %i __4::TestStringTable"
"|* %r %i __5::TestStringTable"
;

#include "TestStringTable-BorderWidth-enum.h"


static void ConfigureBorderWidthMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
