// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestDirector_About
#define _H_TestDirector_About

static const JUtf8Byte* kAboutMenuStr =
"* %i __About::TestDirector"
"|* %i HelpSpecific::JX"
"|* %i __TipOfTheDay::TestDirector %l"
"|* %i __PrintPostScript::TestDirector"
"|* %i __PrintEPS::TestDirector %l"
"|* %i __Quit::TestDirector"
;

#include "TestDirector-About-enum.h"


static void ConfigureAboutMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#?");
	}
};

#endif
