// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestDirector_Test
#define _H_TestDirector_Test

static const JUtf8Byte* kTestMenuStr =
"* %i __NewMainWindow::TestDirector %l"
"|* %i __UserNotification::TestDirector"
"|* %i __FileChooser::TestDirector"
"|* %i __ProgressDisplay::TestDirector %l"
"|* %i __InputFields::TestDirector"
"|* %i __Buttons::TestDirector"
"|* %i __PopupMenus::TestDirector"
"|* %i __Sliders::TestDirector %l"
"|* %i __Partitions::TestDirector"
"|* %i __TabGroup::TestDirector"
"|* %i __StringTable::TestDirector"
"|* %i __NumberTable::TestDirector"
"|* %i __TextEditor::TestDirector"
"|* %i __LinkedDocuments::TestDirector"
"|* %i __DragAndDropText::TestDirector"
"|* %i __ImageViewer::TestDirector"
"|* %i __FileList::TestDirector %l"
"|* %i __SendEmail::TestDirector"
"|* %i __ShowFileContent::TestDirector"
"|* %i __ShowWebPage::TestDirector %l"
"|* %b %i __EnableSmileysMenu::TestDirector %l"
"|* %i __ZombieProcess::TestDirector %l"
"|* %i __PlaceWindowAt00::TestDirector"
"|* %i __PlaceWindowAt3030::TestDirector"
"|* %i __PlaceWindowAt100100::TestDirector"
"|* %i __MoveWindowBy1010::TestDirector"
"|* %i __RaiseAllWindows::TestDirector"
"|* %i __WindowConfig::TestDirector %l"
"|* %i __IdleTaskMutex::TestDirector %l"
"|* %i __ForceBrokenPipeDoesNotDumpCore::TestDirector"
"|* %i __GenerateXErrorDumpsCore::TestDirector"
"|* %i __LockUpFor10SecondsTestMDI::TestDirector %l"
"|* %i __TimingForFontSubstitution::TestDirector"
;

#include "TestDirector-Test-enum.h"


static void ConfigureTestMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#t");
	}
};

#endif
