// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestStringTable_Table
#define _H_TestStringTable_Table

static const JUtf8Byte* kTableMenuStr =
"* %r %i __InsertRow::TestStringTable"
"|* %r %i __DuplicateRow::TestStringTable"
"|* %r %i __MoveRow::TestStringTable"
"|* %r %i __RemoveRow::TestStringTable"
"|* %i __RowBorder::TestStringTable %l"
"|* %r %i __InsertColumn::TestStringTable"
"|* %r %i __DuplicateColumn::TestStringTable"
"|* %r %i __MoveColumn::TestStringTable"
"|* %r %i __RemoveColumn::TestStringTable"
"|* %i __ColumnBorder::TestStringTable %l"
"|* %r %i __SelectCells::TestStringTable"
"|* %r %i __SelectRows::TestStringTable"
"|* %r %i __SelectColumns::TestStringTable %l"
"|* %i __TestSelectionIteratorByRow::TestStringTable"
"|* %i __TestSelectionIteratorByCol::TestStringTable %l"
"|* %i __Add4000RowsEnumMouseActionIsInHeaderFile::TestStringTable"
;

#include "TestStringTable-Table-enum.h"


static void ConfigureTableMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#t");
	}
};

#endif
