// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestPartitionDirector_Vert_enum
#define _H_TestPartitionDirector_Vert_enum

enum {
	kSetVertElasticIndexCmd=1,
};

#endif
