// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestDirector_ChooseSaveFile_enum
#define _H_TestDirector_ChooseSaveFile_enum

enum {
	kChooseFileCmd=1,
	kChooseFileCustomCmd,
	kSaveFileCmd,
	kSaveFileCustomCmd,
	kChooseRPathCmd,
	kChooseRWPathCmd,
};

#endif
