// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestWidget_Actions
#define _H_TestWidget_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i __ChangeSize::TestWidget %l"
"|* %b %i __Fill::TestWidget"
"|* %i __Points::TestWidget %l"
"|* %i __Hide::TestWidget"
"|* %i __Deactivate::TestWidget %l"
"|* %i __HideQuit::TestWidget"
"|* %i __DeactivateQuit::TestWidget %l"
"|* %i __PrintSelectionTargets::TestWidget"
"|* %i __PrintOldSelectionTargetsT10Sec::TestWidget %l"
"|* %i __Advice::TestWidget"
"|* %i __xlsfonts::TestWidget"
"|* %i __empty::TestWidget"
;

#include "TestWidget-Actions-enum.h"


static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#a");
	}
};

#endif
