// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestDirector_PrintPostscript
#define _H_TestDirector_PrintPostscript

static const JUtf8Byte* kPrintPostscriptMenuStr =
"* %i __PageSetup::TestDirector"
"|* %i __Print::TestDirector"
;

#include "TestDirector-PrintPostscript-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigurePrintPostscriptMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kPrintPSCmd + offset, jx_file_print);
};

#endif
