// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TestFileListDirector_File
#define _H_TestFileListDirector_File

static const JUtf8Byte* kFileMenuStr =
"* %i __ShowSelectedFilesInFileManager::TestFileListDirector %l"
"|* %b %i __UseWildcardFilter::TestFileListDirector"
"|* %b %i __UseRegexFilter::TestFileListDirector %l"
"|* %i __Close::TestFileListDirector"
;

enum {
	kShowLocationCmd=1,
	kUseWildcardCmd,
	kUseRegexCmd,
	kCloseCmd,
};

#ifndef _H_jx_af_image_jx_jx_filter_wildcard
#define _H_jx_af_image_jx_jx_filter_wildcard
#include <jx-af/image/jx/jx_filter_wildcard.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_filter_regex
#define _H_jx_af_image_jx_jx_filter_regex
#include <jx-af/image/jx/jx_filter_regex.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
	menu->SetItemImage(kUseWildcardCmd + offset, jx_filter_wildcard);
	menu->SetItemImage(kUseRegexCmd + offset, jx_filter_regex);
};

#endif
