#!/bin/sh

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/code_crusader
LIB=$PRE/usr/lib/jxcb
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

MM_DOC=$PRE/usr/share/doc/makemake
CTAGS_DOC=$PRE/usr/share/doc/ctags

if { test ! -z $PRE; } then
	{
	mkdir -p $BIN $APP $ICON;
	}
fi

# jcc

install -m755 jcc                    $BIN
install -m755 dirdiff/dirdiff        $BIN
install -m755 macros/xml-auto-close  $BIN
install -m755 macros/html-auto-close $BIN

ln -sf jcc $BIN/code_crusader

mkdir -p $LIB
cp lib/*                $LIB
cp -R project_templates $LIB
cp -R text_templates    $LIB
cp -R scripts           $LIB

mkdir -p $DOC/HTML
cp README FAQ menu_strings $DOC
cp -R macros               $DOC
cp -R CPM_rules            $DOC
cp docs_HTML/*             $DOC/HTML

cp desktop/code_crusader.desktop $APP/
cp desktop/code_crusader.xpm     $ICON/

# makemake

install -m755 makemake/makemake  $BIN
install -m755 makemake/makecheck $BIN
install -m755 makemake/maketouch $BIN

mkdir -p $MM_DOC
cp makemake/README             $MM_DOC
cp makemake/Make.header_sample $MM_DOC
cp makemake/Make.files_sample  $MM_DOC

# ctags

install -m755 ctags/ctags $BIN

mkdir -p $PRE/usr/man/man1
cp ctags/ctags.1 $PRE/usr/man/man1

mkdir -p $CTAGS_DOC
cp ctags/COPYING $CTAGS_DOC
cp ctags/FAQ     $CTAGS_DOC
cp ctags/NEWS    $CTAGS_DOC
cp ctags/README  $CTAGS_DOC

# post

if { test -z "$ZIP"; } then
	{
	gunzip $LIB/*.gz;
	}
fi

# ignore gzip errors

exit 0;
