#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/code_mill
LIB=$PRE/usr/lib/code_mill
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# code_mill

install -m755 code_mill $BIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC
cp README COPYING menu_strings $DOC

cp desktop/code_mill.desktop $APP/
cp desktop/code_mill.xpm     $ICON/

# post

if [[ -z $ZIP ]]; then
	gunzip $LIB/*.gz;
fi

# ignore gzip errors

exit 0;
