#!/bin/bash

rm -f  /usr/bin/code_mill;
rm -rf /usr/lib/code_mill;
rm -rf /usr/share/doc/code_mill;
rm -f  `find /usr/share/applications -name 'code_mill*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'code_mill*.xpm'`;
