// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_File
#define _H_MainDirector_File

static const JUtf8Byte* kFileMenuStr =
"* %i Quit::MainDirector"
;

#include "MainDirector-File-enum.h"


static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
};

#endif
