// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Preferences_enum
#define _H_MainDirector_Preferences_enum

enum {
	kPrefsCmd=1,
	kEditToolBarCmd,
	kEditFileWebPrefsCmd,
	kEditMacWinPrefsCmd,
	kSaveWindSizeCmd,
};

#endif
