// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Preferences
#define _H_MainDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __EditPreferences::MainDirector"
"|* %i __EditToolBar::MainDirector"
"|* %i __FileManagerWebBrowser::MainDirector"
"|* %i __MacWinXEmulation::MainDirector %l"
"|* %i __SaveWindowSetupAsDefault::MainDirector"
;

enum {
	kPrefsCmd=1,
	kEditToolBarCmd,
	kEditFileWebPrefsCmd,
	kEditMacWinPrefsCmd,
	kSaveWindSizeCmd,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu) {
	if (JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("p", JString::kNoCopy));
	}
};

#endif
