/******************************************************************************
 GMessageHeaderList.h

	Interface for the GMessageHeaderList class.

	Copyright (C) 1997 by Glenn W. Bach.  All rights reserved.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#ifndef _H_GMessageHeaderList
#define _H_GMessageHeaderList

// Superclass Header
#include <GMessageHeader.h>
#include <JPtrArray-JString.h>

class JString;
class JProgressDisplay;

class GMessageHeaderList : public JPtrArray<GMessageHeader>
{
public:

	static JBoolean OkToCreate(const JString& mailfile);
	static JBoolean Create(const JString& mailfile, GMessageHeaderList** list, JProgressDisplay* pg = NULL);
	GMessageHeaderList(const JString& mailfile, JProgressDisplay* pg = NULL);
	GMessageHeaderList();
	virtual ~GMessageHeaderList();

private:

	JString		itsMailFile;
	JBoolean	itsIsWritable;

private:

	// not allowed

	GMessageHeaderList(const GMessageHeaderList& source);
	const GMessageHeaderList& operator=(const GMessageHeaderList& source);
};

#endif
