/******************************************************************************
 GPOPRetriever.h

	Interface for the GPOPRetriever class

	Copyright © 1998 by Glenn W. Bach.  All rights reserved.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#ifndef _H_GPOPRetriever
#define _H_GPOPRetriever

#include <JMessageProtocol.h>

#include <JPtrArray-JString.h>
#include <JProcess.h>

#include <j_prep_ace.h>
#include <ace/INET_Addr.h>
#include <ace/UNIX_Addr.h>

#include <ace/SOCK_Connector.h>
#include <ace/SOCK_Stream.h>

class GMAccount;

class JLatentPG;
class JOutPipeStream;

class JXGetStringDialog;
class JXTimerTask;

class GPOPRetriever : virtual public JBroadcaster
{
public:

	GPOPRetriever(GMAccount* account);
	virtual ~GPOPRetriever();

	void	CheckMail();

protected:

	virtual void	Receive(JBroadcaster* sender,
								const JBroadcaster::Message& message);

private:

	typedef JMessageProtocol<ACE_SOCK_STREAM>	InetLink;

private:

	InetLink*				itsLink;
	JXGetStringDialog*		itsDialog;
	JString					itsPasswd;
	JString					itsTimeStamp;
	JIndex					itsCurrentIndex;
	JIndex					itsCurrentMode;
	JIndex					itsMessageCount;
	JBoolean				itsMessageFinished;
	JBoolean				itsMessageStarting;
	JString*				itsMessageBuffer;
	JBoolean				itsListStarting;
	JIndex					itsListLinesCount;
	JPtrArray<JString>*		itsReadUIDList;		// not owned
	JPtrArray<JString>*		itsUIDList;
	JArray<JIndex>*			itsNewUIDIndexes;
	JXTimerTask*			itsTimerTask;
	JXTimerTask*			itsDeleteTask;
	JXTimerTask*			itsTimeoutTask;
	JXTimerTask*			itsPGCheckTask;
	JXTimerTask*			itsDeadLinkTask;
	JProcess*				itsProcmailProcess;
	JLatentPG*				itsPG;
	JBoolean				itsSomethingRead;
	JOutPipeStream*			itsOutStream;
	JString					itsAccountName;
	JString					itsFromLine;
	GMAccount*				itsAccount;
	JBoolean				itsBroadcastOnFinish;

private:

	void		SendLine(const JCharacter* line);
	void		SendLine(const JString& line);

	void		WriteMessageToStream();

	void		HandleUIDL();
	JString		EncryptedTimeAndPass();

	void		ConnectToServer();
	void		ReadReturnValue();
	void		SendNextData();
	JBoolean	SaveMessage();
	void		ReadFinished();

	// not allowed

	GPOPRetriever(const GPOPRetriever& source);
	const GPOPRetriever& operator=(const GPOPRetriever& source);

public:

	static const JCharacter* kCheckFinished;
	static const JCharacter* kCheckFailed;

	class CheckFinished : public JBroadcaster::Message
		{
		public:

			CheckFinished()
				:
				JBroadcaster::Message(kCheckFinished)
				{ };
		};

	class CheckFailed : public JBroadcaster::Message
		{
		public:

			CheckFailed()
				:
				JBroadcaster::Message(kCheckFailed)
				{ };
		};

};


#endif
