// code/CBDTreeScanner.h generated by reflex 3.0.10 from code/CBDTreeScanner.l

#ifndef REFLEX_CODE_CBDTREESCANNER_H
#define REFLEX_CODE_CBDTREESCANNER_H
#define IN_HEADER 1
#define REFLEX_VERSION "3.0.10"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_freespace           true
#define REFLEX_OPTION_full                true
#define REFLEX_OPTION_header_file         "code/CBDTreeScanner.h"
#define REFLEX_OPTION_lex                 CreateClasses
#define REFLEX_OPTION_lexer               Scanner
#define REFLEX_OPTION_namespace           CB::DTree
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_outfile             "code/CBDTreeScanner.cpp"
#define REFLEX_OPTION_params              const JString& fileName, const JFAID_t fileID, CBTree* tree, JPtrArray<CBClass>* classList
#define REFLEX_OPTION_token_type          bool
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "code/CBDTreeScanner.l"

/*
Copyright © 1998 by Dustin Laurence.
Copyright © 2021 by John Lindal.

This scanner reads a D file and creates CBClass instances.
*/

#include "CBDClass.h"
#include <JString.h>
#include <JStringIterator.h>
#include <JRegex.h>
#include <JStringPtrMap.h>
#include <JStack.h>
#include <jFileUtil.h>
#include <JFAID.h>
#include <jAssert.h>


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace CB {
namespace DTree {

class Scanner : public reflex::AbstractLexer<reflex::Matcher> {
#line 25 "code/CBDTreeScanner.l"


public:

	virtual ~Scanner();

private:

	JString		itsPackage;
	JInteger	itsCurlyBraceDepth;
	JInteger	itsDepth;
	bool		itsAbstractFlag;
	bool		itsFinalFlag;
	bool		itsTemplateFlag;
	CBClass*	itsCurrentClass;

	JStack<JInteger, JArray<JInteger>>	itsCurlyBraceStack;
	JPtrArray<JString>*					itsNamespaceStack;
	JPtrArray<JString>*					itsAliasKeys;
	JStringPtrMap<JString>*				itsAliasMap;

	JPtrArray<JString>*	itsImportPackages;
	JString				itsImportPackage;
	JString				itsImportAlias;

private:

	void ResetState()
	{
		itsAbstractFlag = false;
		itsFinalFlag    = false;
		itsTemplateFlag = false;
		itsCurrentClass = nullptr;
	}

	void	StoreAlias(const JString& s);

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Scanner(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
#line 63 "code/CBDTreeScanner.l"

	itsNamespaceStack = jnew JPtrArray<JString>(JPtrArrayT::kDeleteAll);
	assert( itsNamespaceStack != nullptr );

	itsAliasKeys = jnew JPtrArray<JString>(JPtrArrayT::kDeleteAll);
	assert( itsAliasKeys != nullptr );

	itsAliasMap = jnew JStringPtrMap<JString>(JPtrArrayT::kDeleteAll);
	assert( itsAliasMap != nullptr );

	itsImportPackages = jnew JPtrArray<JString>(JPtrArrayT::kDeleteAll);
	assert( itsImportPackages != nullptr );

  }
  static const int INITIAL = 0;
  static const int IMPORT_STATE = 1;
  static const int IMPORT_ALIAS_STATE = 2;
  static const int CLASS_NAME_STATE = 3;
  static const int INHERIT_STATE = 4;
  static const int C_COMMENT_STATE = 5;
  static const int CPP_COMMENT_STATE = 6;
  static const int D_COMMENT_STATE = 7;
  static const int STRING_STATE = 8;
  static const int WYSIWYG_STRING_STATE = 9;
  static const int ALT_WYSIWYG_STRING_STATE = 10;
  static const int HEX_STRING_STATE = 11;
  static const int TOKEN_STRING_STATE = 12;
  virtual bool CreateClasses(const JString& fileName, const JFAID_t fileID, CBTree* tree, JPtrArray<CBClass>* classList);
  bool CreateClasses(const reflex::Input& input, const JString& fileName, const JFAID_t fileID, CBTree* tree, JPtrArray<CBClass>* classList)
  {
    in(input);
    return CreateClasses(fileName, fileID, tree, classList);
  }
  bool CreateClasses(const reflex::Input& input, std::ostream *os, const JString& fileName, const JFAID_t fileID, CBTree* tree, JPtrArray<CBClass>* classList)
  {
    in(input);
    if (os)
      out(*os);
    return CreateClasses(fileName, fileID, tree, classList);
  }
};

} // namespace CB
} // namespace DTree

#endif
