// code/CBINIScanner.h generated by reflex 3.0.10 from code/CBINIScanner.ll

#ifndef allow_multiple_includesREFLEX_CODE_CBINISCANNER_H
#define allow_multiple_includesREFLEX_CODE_CBINISCANNER_H
#define allow_multiple_includesIN_HEADER 1
#define REFLEX_VERSION "3.0.10"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_freespace
#undef REFLEX_OPTION_full
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_prefix
#undef REFLEX_OPTION_token_type
#undef REFLEX_OPTION_unicode

#define REFLEX_OPTION_freespace           true
#define REFLEX_OPTION_full                true
#define REFLEX_OPTION_header_file         "code/CBINIScanner.h"
#define REFLEX_OPTION_lex                 NextToken
#define REFLEX_OPTION_lexer               Scanner
#define REFLEX_OPTION_namespace           CB::INI
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_outfile             "code/CBINIScanner.cpp"
#define REFLEX_OPTION_prefix              allow_multiple_includes
#define REFLEX_OPTION_token_type          CBStylingScannerBase::Token
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "code/CBINIScanner.ll"

/*
Copyright © 2013 by John Lindal.

This scanner reads a PHP .ini file and returns CB::INI::Scanner::Tokens.
*/

#include "CBStylingScannerBase.h"
#include <jAssert.h>


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace CB {
namespace INI {

class Scanner : public CBStylingScannerBase {
#line 16 "code/CBINIScanner.ll"


public:

	// these types are ordered to correspond to the type table in CBINIStyler

	enum TokenType
	{
		kUnterminatedString = kEOF+1,
		kNonPrintChar,

		kWhitespace,	// must be the one before the first item in type table

		kSectionName,

		kKeyOrValue,
		kAssignment,
		kArrayIndex,

		kSingleQuoteString,
		kDoubleQuoteString,

		kComment,

		kError			// place holder for CBINIStyler
	};

 public:
  typedef CBStylingScannerBase AbstractBaseLexer;
  Scanner(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  static const int SINGLE_STRING_STATE = 1;
  static const int DOUBLE_STRING_STATE = 2;
  virtual CBStylingScannerBase::Token NextToken(void);
  CBStylingScannerBase::Token NextToken(const reflex::Input& input)
  {
    in(input);
    return NextToken();
  }
  CBStylingScannerBase::Token NextToken(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return NextToken();
  }
};

} // namespace CB
} // namespace INI

#endif
