// code/CBPHPTreeScanner.h generated by reflex 3.0.10 from code/CBPHPTreeScanner.l

#ifndef REFLEX_CODE_CBPHPTREESCANNER_H
#define REFLEX_CODE_CBPHPTREESCANNER_H
#define IN_HEADER 1
#define REFLEX_VERSION "3.0.10"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_freespace           true
#define REFLEX_OPTION_full                true
#define REFLEX_OPTION_header_file         "code/CBPHPTreeScanner.h"
#define REFLEX_OPTION_lex                 CreateClass
#define REFLEX_OPTION_lexer               Scanner
#define REFLEX_OPTION_namespace           CB::PHPTree
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_outfile             "code/CBPHPTreeScanner.cpp"
#define REFLEX_OPTION_params              const JFAID_t fileID, CBTree* tree, CBClass** theClass
#define REFLEX_OPTION_token_type          bool
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "code/CBPHPTreeScanner.l"

/*
Copyright © 2014 by John Lindal.

This scanner reads a PHP file and builds a CBPHPClass.
*/

#include "CBPHPClass.h"
#include <JString.h>
#include <JStringIterator.h>
#include <JFAID.h>
#include <jAssert.h>


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace CB {
namespace PHPTree {

class Scanner : public reflex::AbstractLexer<reflex::Matcher> {
#line 20 "code/CBPHPTreeScanner.l"


public:

	virtual ~Scanner();

private:

	JString	itsPHPNamespace;
	bool	itsAbstractFlag;
	bool	itsFinalFlag;

	JString					itsUseName;
	JStringPtrMap<JString>*	itsUseMap;

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Scanner(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
#line 36 "code/CBPHPTreeScanner.l"

	itsUseMap = jnew JStringPtrMap<JString>(JPtrArrayT::kDeleteAll);
	assert( itsUseMap != nullptr );

  }
  static const int INITIAL = 0;
  static const int NAMESPACE_STATE = 1;
  static const int USE_STATE = 2;
  static const int USE_AS_STATE = 3;
  static const int CLASS_NAME_STATE = 4;
  static const int INHERIT_STATE = 5;
  static const int C_COMMENT_STATE = 6;
  static const int CPP_COMMENT_STATE = 7;
  virtual bool CreateClass(const JFAID_t fileID, CBTree* tree, CBClass** theClass);
  bool CreateClass(const reflex::Input& input, const JFAID_t fileID, CBTree* tree, CBClass** theClass)
  {
    in(input);
    return CreateClass(fileID, tree, theClass);
  }
  bool CreateClass(const reflex::Input& input, std::ostream *os, const JFAID_t fileID, CBTree* tree, CBClass** theClass)
  {
    in(input);
    if (os)
      out(*os);
    return CreateClass(fileID, tree, theClass);
  }
};

} // namespace CB
} // namespace PHPTree

#endif
