#!/bin/bash

rm -f  /usr/bin/glove;
rm -rf /usr/lib/glove;
rm -rf /usr/share/doc/glove;
rm -f  `find /usr/share/applications -name 'glove*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'glove*.xpm'`;
