#ifndef _H_JMMArrayTable
#define _H_JMMArrayTable

/******************************************************************************
 JMMArrayTable.h

	Copyright (C) 1997 by Dustin Laurence.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#include "JMMTable.h"
#include "JArray.h"

class JMMArrayTable : public JMMTable
{
public:

	JMMArrayTable(JMemoryManager* manager, const JBoolean recordDelete);
	virtual ~JMMArrayTable();

	virtual JSize GetAllocatedCount() const override;
	virtual JSize GetAllocatedBytes() const override;
	virtual JSize GetDeletedCount() const override;
	virtual JSize GetTotalCount() const override;

	virtual void PrintAllocated(const JBoolean printInternal = kJFalse) const override;
	virtual void StreamAllocatedForDebug(std::ostream& output, const JMemoryManager::RecordFilter& filter) const override;
	virtual void StreamAllocationSizeHistogram(std::ostream& output) const override;

protected:

	virtual void _AddNewRecord(const JMMRecord& record,
									   const JBoolean checkDoubleAllocation) override;

	virtual JBoolean _SetRecordDeleted(JMMRecord* record, const void* block,
									   const JUtf8Byte* file, const JUInt32 line,
									   const JBoolean isArray) override;

private:

	JArray<JMMRecord>*	itsAllocatedTable;
	JSize				itsAllocatedBytes;
	JArray<JMMRecord>*	itsDeletedTable;
	JSize				itsDeletedCount;

private:

	JSize FindAllocatedBlock(const void* block) const;
	JSize FindDeletedBlock(const void* block) const;

	// not allowed

	JMMArrayTable(const JMMArrayTable& source);
	const JMMArrayTable& operator=(const JMMArrayTable& source);
};

#endif
