#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
LIB=$PRE/lib;
INC=$PRE/include;

mkdir -p $BIN;
pushd bin;
for f in *; do
	install -m755 $f $BIN;
done
popd;

mkdir -p $LIB;
cp lib/* $LIB;

mkdir -p $INC;
cp -r include/* $INC;

./configure package;
