#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
    PRE=/usr/local;
fi

BIN=$PRE/bin;
LIB=$PRE/lib;
INC=$PRE/include;
SHR=$PRE/share;

rm -f $BIN/compile_jstrings \
      $BIN/jx_layout_editor \
      $BIN/jx_memory_debugger \
      $BIN/jx_menu_editor \
      $BIN/jx_project_wizard \
      $BIN/makecheck \
      $BIN/makemake \
      $BIN/maketouch;

rm -f $LIB/libjcore.a \
      $LIB/libjx.a \
      $LIB/libjfs.a \
      $LIB/libjexpr.a \
      $LIB/libj2dplot.a;

rm -rf $INC/jx-af;

rm -rf $SHR/jx_project_wizard \
       $SHR/jxlayout;
