#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/nps_svn_client
LIB=$PRE/usr/lib/nps_svn_client
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# nps_svn_client

install -m755 nps_svn_client $BIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC
cp README COPYING menu_strings $DOC

cp desktop/nps_svn_client.desktop $APP/
cp desktop/nps_svn_client.xpm     $ICON/

# post

if [[ -z $ZIP ]]; then
	gunzip $LIB/*.gz;
fi

# ignore gzip errors

exit 0;
