#!/bin/bash

rm -f  /usr/bin/nps_svn_client;
rm -rf /usr/lib/nps_svn_client;
rm -rf /usr/share/doc/nps_svn_client;
rm -f  `find /usr/share/applications -name 'nps_svn_client*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'nps_svn_client*.xpm'`;
