// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_UndoWidgetDir_Actions
#define _H_UndoWidgetDir_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i __Undo::UndoWidgetDir"
"|* %i __Redo::UndoWidgetDir %l"
"|* %i __Quit::UndoWidgetDir"
;

enum {
	kUndo=1,
	kRedo,
	kQuit,
};


static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
};

#endif
