#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/code_crusader
LIB=$PRE/usr/lib/jxcb
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

MM_DOC=$PRE/usr/share/doc/makemake

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# jcc

install -m755 jcc                    $BIN
install -m755 dirdiff/dirdiff        $BIN
install -m755 macros/xml-auto-close  $BIN
install -m755 macros/html-auto-close $BIN

ln -sf jcc $BIN/code_crusader

mkdir -p $LIB
cp lib/*                $LIB
cp -R project_templates $LIB
cp -R text_templates    $LIB
cp -R scripts           $LIB

mkdir -p $DOC
cp README.md menu_strings $DOC
cp -R macros              $DOC
cp -R CPM_rules           $DOC

cp desktop/code_crusader.desktop $APP/
cp desktop/code_crusader.xpm     $ICON/

# makemake

install -m755 makemake/makemake  $BIN
install -m755 makemake/makecheck $BIN
install -m755 makemake/maketouch $BIN

mkdir -p $MM_DOC
cp makemake/README             $MM_DOC
cp makemake/Make.header_sample $MM_DOC
cp makemake/Make.files_sample  $MM_DOC

# post

if [[ -z $ZIP ]]; then
	gunzip $LIB/*.gz;
fi

# ignore gzip errors

exit 0;
