#!/bin/bash

rm -f  /usr/bin/jcc;
rm -f  /usr/bin/code_crusader;
rm -f  /usr/bin/dirdiff;
rm -f  /usr/bin/xml-auto-close;
rm -f  /usr/bin/html-auto-close;
rm -rf /usr/lib/jxcb;
rm -rf /usr/share/doc/code_crusader;
rm -f  `find /usr/share/applications -name 'code_crusader*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'code_crusader*.xpm'`;

rm -f  /usr/bin/makemake;
rm -f  /usr/bin/makecheck;
rm -f  /usr/bin/maketouch;
rm -rf /usr/share/doc/makemake;
