#!/usr/bin/perl

# usage:   character action
# example: `  =>  $(java-import $p $t)

$path = $ARGV[0];
$line = $ARGV[1];

$result = '';

if ($line =~ /([a-z0-9_]+).$/i)
	{
	$class = $1;
	($lib = $path) =~ s#/src/(main|test)/java/.+#/target/*/WEB-INF/lib/*#;

	foreach $f (glob($lib))
		{
		foreach $line (split(/\n/, `unzip -l $f`))
			{
			if ($line =~ m|([^[:space:]]+)/${class}\.class$|)
				{
				($pkg = $1) =~ s|/|.|g;
				$result .= "import ".$pkg.".$class;\n"
				}
			}
		}

	if ($result)
		{
		foreach (0..length($class))
			{
			print chr(8);
			}
		print $result;
		}
	}
