#!/bin/bash

if [[ ! -d ACE_wrappers/ ]]; then
	if [[ -z $ACE_ROOT ]]; then
		echo "please set ACE_ROOT";
		exit 1;
	else
		ln -sf ${ACE_ROOT} ACE_wrappers;
	fi
fi

VERS=`echo ACE_wrappers/*.*.*`;
if [[ -f $VERS ]]; then
	VERS=${VERS##*/};
else
	if [[ $# < 1 ]]; then
		echo "usage: $0 patch_version";
		exit 1;
	fi

	VERS=$1;
fi

echo "patching version $VERS";

DIR="./patch-$VERS";
if [[ ! -d $DIR ]]; then
	echo "$DIR does not exist - assuming no patches are necessary";
	exit;
fi

for SRC in $DIR/*; do
	f=${SRC##*/};
	echo $f;
	DST=`find ./ACE_wrappers/ -name $f`;
	cp -f $SRC $DST;
done
