#!/bin/sh

rm -f  /usr/bin/jx_memory_debugger;
rm -rf /usr/lib/jx_memory_debugger;
rm -rf /usr/share/doc/jx_memory_debugger;
rm -f  `find /usr/share/applications -name 'jx_memory_debugger*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'jx_memory_debugger*.xpm'`;
