#!/bin/bash

rm -f  /usr/bin/medic;
rm -rf /usr/lib/medic;
rm -rf /usr/share/doc/code_medic;
rm -f  `find /usr/share/applications -name 'code_medic*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'code_medic*.xpm'`;
