// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DialogHelloDir_Text
#define _H_DialogHelloDir_Text

static const JUtf8Byte* kTextMenuStr =
"* %i __ChangeText::DialogHelloDir %l"
"|* %i __Quit::DialogHelloDir"
;

#include "DialogHelloDir-Text-enum.h"


static void ConfigureTextMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#t");
	}
};

#endif
