#!/usr/bin/perl

use strict;

for my $f (@ARGV)
	{
	open(F, '< '.$f);
	my $s1;
	{
		local $/ = undef;
		$s1 = <F>;
	}
	close(F);

	(my $s2 = $s1) =~ s/dynamic_cast\(\s*([^,]+)\s*,\s*([^)]+\s*)\)/dynamic_cast<$1>($2)/g;

	if ($s1 ne $s2)
		{
		print $f,"\n";
		open(F, '> '.$f);
		print F $s2;
		close(F);
		}
	}
