#!/usr/bin/perl

if (!($name = $ARGV[0]))
	{
	print STDERR "usage:  $0 site_name\n";
	exit(1);
	}

while (1)
	{
	$code = 1 + int(16 * rand());
	$str  = "";

	@name = split(//, $name);
	foreach $c (@name)
		{
		$c = chr(ord($c) ^ $code);
		if ($c eq "'" || $c eq "\"")
			{
			$str .= "\\";
			}
		$str .= $c;
		}

	if ($str !~ /\$|`/)
		{
		last;
		}
	}

print "-DSITE_CODE=$code '-DSITE_NAME=\\\"",$str,"\\\"'";
