#!/usr/bin/perl

# Removes all links except "mailto:".
# Replaces header and footer with NPS boilerplate.

sub ReadFile($)
{
	local $/ = undef;
	open(F, "< $_[0]");
	return <F>;
}

foreach $file (@ARGV)
	{
	# read file

	$data = ReadFile($file);

	$data  =~ /<title>\s*(.+?)\s*<\/title>/;
	$title = $1;

	$data =~ s/(<font[^>]*>)/$1\n$title<p><hr><p>/;

	# can't remove </a>, because of remaining mailto links

	$data =~ s/<a href=[^m][^>]*>//g;

	# save result

	unlink($file);
	open(F, "> $file");
	print F $data;
	}
