#!/usr/bin/perl

# Changes prefix of symbol name in all source files (.cc, .h, .tmpl, .l,
# .y, .fd) in and below directory in which the script is run.

sub ReadFile($)
{
	local $/ = undef;
	open(F, "< $_[0]");
	return <F>;
}

if (!($orig_name = $ARGV[0]) ||
	!($new_name  = $ARGV[1]))
	{
	print "usage:  $0 orig_name new_name\n";
	exit;
	}

open(L, "find . -regex '.+\\.\\(cc\\|cpp\\|fd\\|[tp]?h\\|tmpl\\|[ly]\\)' |");

while ($file = <L>)
	{
	chomp($file);
	$orig_data = $data = ReadFile($file);

	$data =~ s/\b$orig_name\b/$new_name/go;
	$data =~ s/\b_H_$orig_name\b/_H_$new_name/go;

	if ($data ne $orig_data)
		{
		print $file,"\n";

		$bak = $file."~";
		rename($file, $bak) unless -f $bak;

		$file =~ s|/$orig_name(\.\w+)$|/$new_name$1|o;
		open(F, "> $file");
		print F $data;
		}
	}
