#!/bin/sh

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

XBIN=$PRE/usr/X11R6/bin
DOC=$PRE/usr/share/doc/systemg
LIB=$PRE/usr/lib/systemg
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if { test ! -z $PRE; } then
	{
	mkdir -p $XBIN;
	mkdir -p $APP;
	mkdir -p $ICON;
	}
fi

# systemg

install -m755 systemg $XBIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC/HTML
cp README FAQ COPYING menu_strings $DOC
cp docs_HTML/*                     $DOC/HTML

cp desktop/systemg.desktop        $APP/
cp desktop/systemg_choose.desktop $APP/
cp desktop/systemg.xpm            $ICON/

# post

if { test -z "$ZIP"; } then
	{
	gunzip $LIB/*.gz;
	}
fi
