// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ChooseWidgetDialog_Widget_enum
#define _H_ChooseWidgetDialog_Widget_enum

enum {
	kCustomWidgetIndex=1,
	kStaticTextIndex,
	kInputFieldIndex,
	kIntegerInputIndex,
	kFloatInputIndex,
	kCharInputIndex,
	kPasswordInputIndex,
	kTextButtonIndex,
	kTextCheckboxIndex,
	kRadioGroupIndex,
	kTextRadioButtonIndex,
	kWidgetSetIndex,
};

#endif
