// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ChooseWidgetDialog_Widget_enum
#define _H_ChooseWidgetDialog_Widget_enum

enum {
	kCustomWidgetIndex=1,
	kStaticTextIndex,
	kImageWidgetIndex,
	kInputFieldIndex,
	kIntegerInputIndex,
	kFloatInputIndex,
	kCharInputIndex,
	kPasswordInputIndex,
	kTextButtonIndex,
	kImageButtonIndex,
	kTextCheckboxIndex,
	kImageCheckboxIndex,
	kRadioGroupIndex,
	kTextRadioButtonIndex,
	kImageRadioButtonIndex,
	kMenuBarIndex,
	kTextMenuIndex,
	kImageMenuIndex,
	kScrollbarSetIndex,
	kToolBarIndex,
	kHorizPartitionIndex,
	kVertPartitionIndex,
	kTabGroupIndex,
	kWidgetSetIndex,
	kSliderIndex,
	kLevelControlIndex,
	kProgressIndicatorIndex,
	kStringHistoryMenuIndex,
	kFlatRectIndex,
	kBorderRectIndex,
	kUpRectIndex,
	kDownRectIndex,
	kEngravedRectIndex,
	kEmbossedRectIndex,
	kFileInputIndex,
	kFileHistoryMenuIndex,
	kPathInputIndex,
	kPathHistoryMenuIndex,
	kNewDirButtonIndex,
};

#endif
