// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_LayoutContainer_Arrange_enum
#define _H_LayoutContainer_Arrange_enum

enum {
	kAlignLeftCmd=1,
	kAlignHorizCenterCmd,
	kAlignRightCmd,
	kAlignTopCmd,
	kAlignVertCenterCmd,
	kAlignBottomCmd,
	kDistrHorizCmd,
	kDistrVertCmd,
	kExpandHorizCmd,
	kExpandVertCmd,
	kDecrementTabIndexCmd,
	kIncrementTabIndexCmd,
};

#endif
