// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_LayoutDocument_Grid
#define _H_LayoutDocument_Grid

static const JUtf8Byte* kGridMenuStr =
"* %r %i __Grid5::LayoutDocument"
"|* %r %i __Grid10::LayoutDocument"
;

#include "LayoutDocument-Grid-enum.h"


static void ConfigureGridMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
