// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_LayoutDocument_File
#define _H_LayoutDocument_File

static const JUtf8Byte* kFileMenuStr =
"* %i New::LayoutDocument %l"
"|* %i Open::LayoutDocument"
"|* %i Recent::LayoutDocument %l"
"|* %i Save::LayoutDocument"
"|* %i SaveAs::LayoutDocument"
"|* %i SaveCopyAs::LayoutDocument"
"|* %i Revert::LayoutDocument"
"|* %i SaveAll::LayoutDocument %l"
"|* %i ShowInFileMgr::LayoutDocument %l"
"|* %i CloseWindow::LayoutDocument %l"
"|* %i Quit::LayoutDocument"
;

#include "LayoutDocument-File-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_new
#define _H_jx_af_image_jx_jx_file_new
#include <jx-af/image/jx/jx_file_new.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_save
#define _H_jx_af_image_jx_jx_file_save
#include <jx-af/image/jx/jx_file_save.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_revert_to_saved
#define _H_jx_af_image_jx_jx_file_revert_to_saved
#include <jx-af/image/jx/jx_file_revert_to_saved.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_save_all
#define _H_jx_af_image_jx_jx_file_save_all
#include <jx-af/image/jx/jx_file_save_all.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
	menu->SetItemImage(kNewCmd + offset, jx_file_new);
	menu->SetItemImage(kOpenCmd + offset, jx_file_open);
	menu->SetItemImage(kSaveCmd + offset, jx_file_save);
	menu->SetItemImage(kRevertCmd + offset, jx_file_revert_to_saved);
	menu->SetItemImage(kSaveAllCmd + offset, jx_file_save_all);
};

#endif
