// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MenuPanel_ArrowDirection_enum
#define _H_MenuPanel_ArrowDirection_enum

enum {
	kArrowUpIndex=1,
	kArrowDownIndex,
};

#endif
