// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_WidgetParametersDialog_HSizing
#define _H_WidgetParametersDialog_HSizing

static const JUtf8Byte* kHorizontalSizingMenuStr =
"* %r %i __FixedLeft::WidgetParametersDialog"
"|* %r %i __FixedRight::WidgetParametersDialog"
"|* %r %i __Elastic::WidgetParametersDialog"
;

#include "WidgetParametersDialog-HSizing-enum.h"

#ifndef _H_align_left
#define _H_align_left
#include "align_left.xpm"
#endif
#ifndef _H_align_right
#define _H_align_right
#include "align_right.xpm"
#endif
#ifndef _H_expand_horiz
#define _H_expand_horiz
#include "expand_horiz.xpm"
#endif

static void ConfigureHorizontalSizingMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kFixedLeftCmd + offset, align_left);
	menu->SetItemImage(kFixedRightCmd + offset, align_right);
	menu->SetItemImage(kHElasticCmd + offset, expand_horiz);
};

#endif
