// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_WidgetParametersDialog_VSizing_enum
#define _H_WidgetParametersDialog_VSizing_enum

enum {
	kFixedTopCmd=1,
	kFixedBottomCmd,
	kVElasticCmd,
};

#endif
