#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/drakon
LIB=$PRE/usr/lib/drakon
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# drakon

install -m755 drakon $BIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC
cp README COPYING menu_strings $DOC

cp desktop/drakon.desktop $APP/
cp desktop/drakon.xpm     $ICON/

# post

if [[ -z $ZIP ]]; then
	gunzip $LIB/*.gz;
fi

# ignore gzip errors

exit 0;
