#!/bin/bash

rm -f  /usr/bin/drakon;
rm -rf /usr/lib/drakon;
rm -rf /usr/share/doc/drakon;
rm -f  `find /usr/share/applications -name 'drakon*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'drakon*.xpm'`;
