const JCharacter* kLicenseText =
"Arrow, and associated documentation files (the \"Software\") are "
"copyright (c) 2000 by Glenn Bach (the \"Author\").\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR "
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL "
"THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN "
"AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN "
"CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"\n"
"This file shall be included unchanged in all copies or substantial portions "
"of the Software.\n"
"\n"
"---------------\n"
"\n"
"The Software may be freely redistributed in its original form.\n"
"\n"
"If you make modifications to the Software, you may distribute them in a "
"separate package as a set of patches.  Modifications must not alter or "
"remove this license or any copyright notices.  The Authors are granted a "
"non-exclusive right to distribute and/or merge your modifications in "
"future releases.\n"
"\n"
"If you distribute a compiled version of the modified Software, it must "
"clearly display the fact that it is not built from the original "
"distribution and must give clear directions for obtaining both the "
"original distribution and the source for the modifications, without any "
"charge beyond the costs of data transfer.\n"
"\n"
"---------------\n"
"\n"
"The source to Arrow is provided primarily so people can compile it on UNIX "
"systems to which the author does not have access.  To help others who have "
"the same system as you, please consider building the binary and making it "
"available via ftp on the main Arrow ftp site.  (Mirror sites are always "
"welcome, too.)\n"
"\n"
"If you need to modify the source, either to get it to compile on your "
"system or to enhance it, you will save yourself a lot of trouble by first "
"discussing it with me because (1) it might already have been done in a "
"newer release, (2) I can check that it won't disrupt any of the myriad "
"subtle interactions between components, and (3) I might think of an easier "
"way to do it.\n"
"\n"
"Successful changes will propagate by being merged into the master source "
"and released in the next version.  I want to maintain a single distribution "
"because this will insure that nobody will be cut off from using future "
"upgrades.\n"
"\n"
"---------------\n"
"\n"
"If you accept this license, press the \"Yes\" button below. If you do not "
"accept this license, press the \"No\" button below.\n";
