#!/bin/csh
set pfile = JPtrArray-$1.cc
touch $pfile
echo "#include <$1.h>" > $pfile
echo "#include <JArray.tmpls>" >> $pfile
echo "#define JTemplateType $1" >> $pfile
echo "#include <JPtrArray.tmpls>" >> $pfile

