#!/bin/sh

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

XBIN=$PRE/usr/X11R6/bin
DOC=$PRE/usr/share/doc/glove
LIB=$PRE/usr/lib/glove
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if { test ! -z $PRE; } then
	{
	mkdir -p $XBIN;
	mkdir -p $APP;
	mkdir -p $ICON;
	}
fi

# glove

install -m755 glove $XBIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC/HTML
cp README FAQ COPYING menu_strings $DOC
cp docs_HTML/*                     $DOC/HTML

cp desktop/glove.desktop $APP/
cp desktop/glove.xpm     $ICON/

# post

if { test -z "$ZIP"; } then
	{
	gunzip $LIB/*.gz;
	}
fi
