/******************************************************************************
 sptest.cc

	A test program for Spencer's regex package.

	Copyright (C) 1997 by Dustin Laurence.  All rights reserved.
	
	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#include <sys/types.h>
#include <regex.h>
#include <jAssert.h>

/******************************************************************************
 main

 *****************************************************************************/

int
main()
{
	regex_t regex;

	char* pattern = "[[:<:]]";

	if ( regcomp(&regex, pattern, REG_EXTENDED) )
		{
		std::cout << "   Failed to compile" << std::endl;
		}

	regmatch_t match;

	char*  string = " abc def ";
	size_t strLen = strlen(string);

	match.rm_so = 0;
	match.rm_eo = strLen;
	while ( !regexec(&regex, string, 1, &match, REG_STARTEND) )
		{
		std::cout << "Found match (" << match.rm_so << ", " << match.rm_eo << ")" << std::endl;
		match.rm_so = match.rm_eo + 1;
		match.rm_eo = strLen;
		}

	return 0;
}
