/******************************************************************************
 testrand.cc

	Test random number code.

	Copyright © 1997 by Dustin Laurence.  All rights reserved.
	
	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#include <unistd.h>
#include <JStrValue.h>
#include <JMMRecord.h>
#include <JHashRecord.h>

#include <jAssert.h>

/******************************************************************************
 main

 *****************************************************************************/

int
main()
{
	cout << "\nTest system parameters relevant to JHash" << endl;

	cout << "\n   system page size: " << getpagesize() << endl;

	cout << endl;

	JMMRecord scratch1;
	scratch1.PrintLayout();

	JHashRecord< JStrValue<int> > scratch2;
	scratch2.PrintLayout();

	return 0;
}
