/******************************************************************************
 testmap.cc

	Test code for the JStringMap class and related code.

	Copyright (C) 1997 by Dustin Laurence.  All rights reserved.

	Base code generated by Codemill v0.1.0

 *****************************************************************************/

#include <JStringMap.h>
#include <JStringMapCursor.h>
#include <string.h>

//#include <JMemoryManager.h>

#include <jAssert.h>

	void PrintError(long line);

	const JSize gNumStrings = 16;

/******************************************************************************
 main

 *****************************************************************************/

int
main()
{
	JSize i;

	std::cout << "Beginning JStringMap test.  No news is good news." << std::endl;

	const JCharacter* keyConst = "testkey";
	JCharacter* const key = jnew JCharacter[strlen(keyConst)+1];
	strcpy(key, keyConst);

	{
		JStringMap<int> map(kJFalse);

		int v;

		if ( map.GetElement(key, &v) )
			{
			PrintError(__LINE__);
			std::cout << "   Found a non-existent key" << std::endl;
			}

		map.SetElement(key, 42);

		v = 10;
		if ( map.GetElement(key, &v) )
			{
			if (v != 42)
				{
				PrintError(__LINE__);
				std::cout << "   Got value " << v << ", should be 42" << std::endl;
				}
			}
		else
			{
			PrintError(__LINE__);
			std::cout << "   Could not retrieve key value" << std::endl;
			}

		key[0] = 'T';

	// Verify that the map is using the original key, not a copy
		if ( map.GetElement("testkey", &v) )
			{
			PrintError(__LINE__);
			std::cout << "   Retrieved bad key key value" << std::endl;
			}

		// This will fail because we've broken the table; the hash value didn't
		// change even though the key did
		if ( map.GetElement("Testkey", &v) )
			{
			PrintError(__LINE__);
			std::cout << "   Found a non-existent key" << std::endl;
			}

		// Fix table
		key[0] = 't';
		if ( !map.GetElement("testkey", &v) )
			{
			PrintError(__LINE__);
			std::cout << "   Couldn't find key!" << std::endl;
			}

		v = 10;
		if ( map.GetElement("testkey", &v) )
			{
			if (v != 42)
				{
				PrintError(__LINE__);
				std::cout << "   Got value " << v << ", should be 42" << std::endl;
				}
			}
		else
			{
			PrintError(__LINE__);
			std::cout << "   Could not retrieve key value" << std::endl;
			}

		if ( !map.RemoveElement("testkey") )
			{
			PrintError(__LINE__);
			std::cout << "   Unable to remove element" << std::endl;
			}

		if ( map.GetElement("testkey", &v) )
			{
			PrintError(__LINE__);
			std::cout << "   Found a non-existent key" << std::endl;
			}
	}

//	JMemoryManager::Instance()->PrintMemoryStats();

/***
	Play around with inserting and removing a bunch of keys
 ***/

	{
		JStringMap<int> map(0); // Ridiculous table size to really exercise resizer

		if (map.GetElementCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map should be empty!" << std::endl;
			}
		if (map.GetLoadCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map should not have deleted elements!" << std::endl;
			}

// Search for keys, all should fail
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
			int v;
			if ( map.GetElement(key, &v) )
				{
				PrintError(__LINE__);
				std::cout << "   Found non-existent key \"" << key << "\"" << std::endl;
				}
			}
		if (map.GetElementCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map should be empty!" << std::endl;
			}
		if (map.GetLoadCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map should not have deleted elements!" << std::endl;
			}

// Insert keys
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
	//		std::cout << "Inserting string \"" << key << "\" with fill/load factor "
	//		     << map.GetFillFactor() << "/" << map.GetLoadFactor() << std::endl;
			if ( !map.SetNewElement(key, i+42) )
				{
				PrintError(__LINE__);
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}
		{
// Compare with cursor
		JSize count = 0;
		JStringMapCursor<int> cursor(&map);
		while ( cursor.Next() )
			{
			const JCharacter* thisKey = cursor.GetKey();
			int value = cursor.GetValue();
			if (value - 42 != thisKey[0] - 'A')
				{
				PrintError(__LINE__);
				std::cout << "   Cursor found value " << value << ", should have been "
					 << (int) thisKey[0] << "!" << std::endl;
				}
			key[0] = value - 42 + 'A';
			if (strcmp(key, thisKey) != 0)
				{
				PrintError(__LINE__);
				std::cout << "   Cursor found invalid key!" << std::endl;
				}
			++count;
			}
		if (count != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Cursor counted wrong number of elements!" << std::endl;
			}
		}

// Search for keys, should all succeed
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
			int v;
			if ( !map.GetElement(key, &v) )
				{
				PrintError(__LINE__);
				std::cout << "   Could not retrieve key \"" << key << "\"" << std::endl;
				}
			else
				{
				if (JSize(v) != i+42)
					{
					PrintError(__LINE__);
					std::cout << "   Key \"" << key << "\" has value " << v << " instead of "
						 << i+42 << std::endl;
					}
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Search for other keys, all should fail
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'a' + i;
			int v;
			if ( map.GetElement(key, &v) )
				{
				PrintError(__LINE__);
				std::cout << "   Found non-existent key \"" << key << "\"" << std::endl;
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Modify values
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
	//		std::cout << "Changing value of string \"" << key << "\" with fill/load factor "
	//		     << map.GetFillFactor() << "/" << map.GetLoadFactor() << std::endl;
			if ( !map.SetOldElement(key, 99+i) )
				{
				PrintError(__LINE__);
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Search for keys, should all succeed
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
			int v;
			if ( !map.GetElement(key, &v) )
				{
				PrintError(__LINE__);
				std::cout << "   Could not retrieve key \"" << key << "\"" << std::endl;
				}
			else
				{
				if (JSize(v) != i+99)
					{
					PrintError(__LINE__);
					std::cout << "   Key \"" << key << "\" has value " << v << " instead of "
						 << i+99 << std::endl;
					}
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Search for other keys, all should fail
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'a' + i;
			int v;
			if ( map.GetElement(key, &v) )
				{
				PrintError(__LINE__);
				std::cout << "   Found non-existent key \"" << key << "\"" << std::endl;
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Remove other keys, all should fail
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'a' + i;
			if ( map.RemoveElement(key) )
				{
				PrintError(__LINE__);
				std::cout << "   Removal of non-existent key succeeded!" << std::endl;
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Remove keys, all should succeed
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
	//		std::cout << "Removing string \"" << key << "\" with fill/load factor "
	//		     << map.GetFillFactor() << "/" << map.GetLoadFactor() << std::endl;
			if (!map.RemoveElement(key))
				{
				PrintError(__LINE__);
				std::cout << "   Removal failed!" << std::endl;
std::cout << "   Map still contains " << map.GetElementCount() << " keys!" << std::endl;
				}
			}
		if (map.GetElementCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains elements!" << std::endl;
			}
		if (map.GetLoadCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains deleted elements!" << std::endl;
			}

// Remove other keys, all should fail
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'a' + i;
			if ( map.RemoveElement(key) )
				{
				PrintError(__LINE__);
				std::cout << "   Removal of non-existent key succeeded!" << std::endl;
				}
			}
		if (map.GetElementCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains elements!" << std::endl;
			}
		if (map.GetLoadCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains deleted elements!" << std::endl;
			}

// Re-insert
		for (i=0;i<gNumStrings;i++)
			{
			key[0] = 'A' + i;
	//		std::cout << "Inserting string \"" << key << "\" with fill/load factor "
	//		     << map.GetFillFactor() << "/" << map.GetLoadFactor() << std::endl;
			if ( !map.SetNewElement(key, -i) )
				{
				PrintError(__LINE__);
				}
			}
		if (map.GetElementCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains wrong number of elements!" << std::endl;
			}
		if (map.GetLoadCount() != gNumStrings)
			{
			PrintError(__LINE__);
			std::cout << "   Map contains extra deleted elements!" << std::endl;
			}

// Remove them all at once
		map.RemoveAll();
		if (map.GetElementCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains elements!" << std::endl;
			}
		if (map.GetLoadCount() != 0)
			{
			PrintError(__LINE__);
			std::cout << "   Map still contains deleted elements!" << std::endl;
			}
	//	std::cout << "RemoveAll left fill/load factor " << map.GetFillFactor()
	//	     << "/" << map.GetLoadFactor()<< std::endl;
	}

	jdelete[] key;

	std::cout << "Finished JStringMap test.  If nothing printed out, it passed." << std::endl;

//	JMemoryManager::Instance()->SetPrintExitStats(kJTrue);

	return 0;
}

/******************************************************************************
 PrintError

 *****************************************************************************/

void
PrintError
	(
	long line
	)
{
	std::cout << "*** testmap error at line " << line << std::endl;
}