#!/bin/sh

# With no arguments, this script must install from an unpacked tgz.

PRE=$1
ZIP=$2

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/nps-ssh-askpass
LIB=$PRE/usr/lib/nps-ssh-askpass

if { test ! -z $PRE; } then
	{
	mkdir -p $BIN;
	}
fi

# nps-ssh-askpass

install -m755 nps-ssh-askpass $BIN

mkdir -p $LIB
cp lib/* $LIB

mkdir -p $DOC
cp README COPYING $DOC

# post

if { test -z "$ZIP"; } then
	{
	gunzip $LIB/*.gz;
	}
fi

# ignore gzip errors

exit 0;
