#include <jTypes.h>
static const JUtf8Byte* kJCoreDefaultStringData[] = {
"1\nJUnsupportedVCS \"$file is either not managed by a version control system or is managed by an unsupported system.\"\nJPathContainsLoop2 \"At least one of \\\"$name1\\\" or \\\"$name2\\\" contains a loop caused by symbolic links.\"\nOtherError::JPrefsManager \"The preferences cannot be used because:\n\n$msg\"\nJWouldHaveBlocked \"The requested operation would have blocked and the stream is set to non-blocking.\"\nSIGFPE::jSignal \"floating point exception (SIGFPE)\"\nJUnexpectedError \"An unexpected err",
"or ($err) occured -- please contact the developer so the situation can be accommodated in the future.\"\nJDirectoryBusy \"\\\"$name\\\" cannot be removed because it is being used by another program.\"\nSearching::jDirUtil \"Searching for \\\"$name\\\"...\"\nJAccessDenied \"You are not allowed to create or access \\\"$name\\\".\"\nSIGPIPE::jSignal \"broken pipe (SIGPIPE)\"\nDirectoryDoesNotExist::JTextChooseSaveFile \"That directory doesn't exist.  Try again?\"\nJNonBlockedSignal \"A non-blocked signal was",
" received which interrupted the operation.\"\nJDirEntryAlreadyExists \"\\\"$name\\\" already exists.\"\nSIGBUS::jSignal \"bus error (SIGBUS)\"\nJComponentNotDirectory \"Some part of \\\"$name\\\" is not a directory.\"\nStatusTerminated::jProcessUtil \"Program terminated by $signal\"\nJCantRenameToNonemptyDirectory \"You cannot rename a directory to an existing, non-empty directory.\"\nJProgramNotAvailable \"The program \\\"$name\\\" either does not exist or is not in any of the directories on the current ",
"execution path.\"\nTrailingBackslash::JSubstitute \"The backslash symbol (\\\\) must be followed by a character.\"\nJAccessDenied2 \"You are not allowed to create or access at least one of \\\"$name1\\\" or \\\"$name2\\\".\"\nJNegativeDescriptor \"At least one of the file descriptors is negative.\"\nStatusSuccess::jProcessUtil \"Program finished successfully\"\nJNameTooLong \"The specified pathname is too long.\"\nSIGSEGV::jSignal \"segmentation fault (SIGSEGV)\"\nFileExists::JTextChooseSaveFile \"That fi",
"le already exists.  Replace it?\"\nFileAlreadyOpen::JFileArray \"\\\"$name\\\" is already open.\"\nJNoHomeDirectory \"You do not have a home directory.\"\nJBadPath2 \"At least of one \\\"$name1\\\" or \\\"$name2\\\" is invalid.\"\nJFileSystemReadOnly \"You cannot write to a read-only file system.\"\nJDirEntryDoesNotExist \"\\\"$name\\\" does not exist.\"\nFileDoesNotExist::JTextChooseSaveFile \"That file doesn't exist.  Try again?\"\nJInvalidOpenMode \"The requested method of opening \\\"$name\\\" is inva",
"lid.\"\nJGeneralIO \"A general I/O error (errno=EIO) occured.\"\nJBadPath \"\\\"$name\\\" is invalid.\"\nUnknownFileType::JImage \"\\\"$name\\\" either does not contain an image or uses an supported format.\"\nSIGALRM::jSignal \"timer signal from alarm (SIGALRM)\"\nJNoProcessMemory \"There is not enough free memory to complete the operation.\"\nJCantRenameFileToDirectory \"You cannot rename \\\"$old_name\\\" to \\\"$new_name\\\" because the former is a file while the latter is a directory\"\nSIGABRT::jSig",
"nal \"call from abort() (SIGABRT)\"\nFileIsNotPNG::JImage \"\\\"$name\\\" does not contain a PNG.\"\nGIFNotAvailable::JImage \"The GIF format is not supported.\"\nSIGTERM::jSignal \"termination signal (SIGTERM)\"\nJFileBusy \"\\\"$name\\\" cannot be replaced because it is being used by another program.\"\nJRemindNewVersion \"An improved version of this program ($vers) is available for download from $site.\n\nWould you like to go there now to download it?\"\nFileIsNotGIF::JImage \"\\\"$name\\\" does not co",
"ntain a GIF.\"\nPrinting::JPSPrinter \"Printing page...\"\nIllegalControlChar::JSubstitute \"The control character sequence (\\\\c) must be followed by a character in the ASCII table between A and underscore (_) inclusive.\"\nJIsADirectory \"An operation which is only legal on a file was attempted on a directory.\"\nStatusErrorCode::jProcessUtil \"Program returned error code $code\"\nSIGINT::jSignal \"interrupt signal (SIGINT)\"\nFileIsNotXPM::JImage \"\\\"$name\\\" does not contain an XPM.\"\nWrongSignat",
"ure::JFileArray \"\\\"$name\\\" has the wrong signature.\"\nunknown::jSignal \"signal $name\"\nDirectoryNotWritable::JTextChooseSaveFile \"That directory isn't writable.  Try again?\"\nFileIsNotJPEG::JImage \"\\\"$name\\\" does not contain a JPEG.\"\nSIGILL::jSignal \"illegal instruction (SIGILL)\"\nSIGSTOP::jSignal \"stop signal (SIGSTOP)\"\nJTriedToRemoveDirectory \"remove() can only remove files, not directories.\"\nJMemoryNotReadable \"An attempt was made to read from memory without read permission.\"",
"\nScanning::JDirInfo \"Scanning directory...\"\nNotEmbeddedFile::JFileArray \"The specified element ($index) is not an embedded JFileArray.\"\nError::JEPSPrinter \"Unable to create the file.  Please check that the directory is writable and that the disk is not full.\"\nJDeviceFull \"A write was attempted to a device with insufficient room to accept the data.\"\nWrongSite::jSysUtil \"This copy of $name is only for use on computers that are part of $site.\n\nYou can obtain a usable copy of this program from",
":\n\n$url\"\nFileNotWritable::JFileArray \"\\\"$name\\\" cannot be opened because you do not have permission to write to it.\"\nJUnknownError \"An unknown error ($err) occurred.\"\nJNoKernelMemory \"There is not enough free memory for the kernel to complete the operation.  (Your computer is in big trouble!)\"\nJCantRenameAcrossFilesystems \"You cannot rename a file so that it moves to a different file system.\"\nJMemoryNotWriteable \"An attempt was made to write to memory without write permission.\"\nJToo",
"ManyDescriptorsOpen \"The program is not allowed to open any more files.\"\nNoHomeDirectory::JPrefsFile \"Unable to create a preferences file because you don't have a home directory.\"\nSIGKILL::jSignal \"kill signal (SIGKILL)\"\nJDirectoryCantBeOwnChild \"A directory cannot be renamed so that it becomes a sub-directory of itself.\"\nJPathContainsLoop \"\\\"$name\\\" contains a loop caused by symbolic links.\"\nJSegFault \"Recoverable segmentation fault: the programmer screwed up!\"\nNewerVersion::JPrefsM",
"anager \"The preferences file is unreadable because it has been modified by a newer version of this program.\"\nPrinting::JPTPrinter \"Printing page...\"\nJComponentNotDirectory2 \"Some part of \\\"$name1\\\" or \\\"$name2\\\" is not a directory.\"\nPNGNotAvailable::JImage \"The PNG format is not supported.\"\nJNotSymbolicLink \"\\\"$name\\\" is not a symbolic link.\"\nCRM2CaretAction::JTextEditor \"Coerce paragraph margins\"\nCRMCaretAction::JTextEditor \"Clean paragraph margins\"\nTooManyColors::JImage ",
"\"The image contains too many colors.\"\nStatusKill::jProcessUtil \"Program terminated by SIGKILL\"\nJNoError \"No errors occurred.\"\nCRM2SelectionAction::JTextEditor \"Coerce margins for selection\"\nCRMSelectionAction::JTextEditor \"Clean margins for selection\"\nJNotCompressed \"\\\"$name\\\" is not compressed.\"\nJPEGNotAvailable::JImage \"The JPEG format is not supported.\"\nConvertFromDOS::JTextEditor \"Converting from DOS format...\"\nJTooManyLinks \"Renaming \\\"$name\\\" would exceed the maximum",
" allowed number of file system links.\"\nReplacingText::JStyledText \"Replacing text...\"\nJInvalidDescriptor \"At least one of the file descriptors was invalid.\"\nSIGQUIT::jSignal \"quit signal (SIGQUIT)\"\nJDescriptorNotOpen \"At least one of the file descriptors does not refer to an open file.\"\nFileNotWritable::JTextChooseSaveFile \"That file isn't writable.  Try again?\"\nJFileSystemFull \"The file system does not have enough free space left.\"\nStatusUnknown::jProcessUtil \"Program terminated for ",
"unknown reason\"\nJDirectoryNotEmpty \"\\\"$name\\\" cannot be removed because it is not empty.\"\nStatusStopped::jProcessUtil \"Program stopped by $signal\"\nFileIsNotXBM::JImage \"\\\"$name\\\" does not contain an XBM.\"\nLoneDollar::JSubstitute \"The dollar symbol ($) must be followed by a variable name.\"\nWrongVersion::JPrefsManager \"The preferences file has the wrong version.\"\nError::JPSPrinter \"An error occurred while trying to print.  Please check that the disk is not full.\"\n",
NULL };
