// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JX2DPlotWidget_Cursor_enum
#define _H_JX2DPlotWidget_Cursor_enum

enum {
	kXCursorCmd=1,
	kYCursorCmd,
	kDualCursorsCmd,
	kMarkCursorCmd,
	kMarkAllVisCursorsCmd,
	kRemoveMarkIndex,
	kRemoveAllMarksCmd,
	kShowMarkWindowCmd,
};

#endif
