// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JX2DPlotPrintEPSDialog_Unit
#define _H_JX2DPlotPrintEPSDialog_Unit

static const JUtf8Byte* kUnitMenuStr =
"* %r %i __mm::JX2DPlotPrintEPSDialog"
"|* %r %i __cm::JX2DPlotPrintEPSDialog"
"|* %r %i __inches::JX2DPlotPrintEPSDialog"
;

#include "JX2DPlotPrintEPSDialog-Unit-enum.h"


static void ConfigureUnitMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
