// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MenuTable_Type
#define _H_MenuTable_Type

static const JUtf8Byte* kTypeMenuStr =
"* %r %i __Plain::MenuTable"
"|* %r %i __Checkbox::MenuTable"
"|* %r %i __RadioButton::MenuTable"
;

enum {
	kPlainCmd=1,
	kCheckboxCmd,
	kRadioCmd,
};



#endif
