// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MenuTable_Table_enum
#define _H_MenuTable_Table_enum

enum {
	kAppendCmd=1,
	kDuplicateCmd,
	kImportCmd,
};

#endif
