// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXInputField_Context_enum
#define _H_JXInputField_Context_enum

enum {
	__Undo=1,
	__Cut,
	__Copy,
	__Paste,
	__Clear,
	__SelectAll,
};

#endif
