// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXTEBase_Search_enum
#define _H_JXTEBase_Search_enum

enum {
	__FindDialog_Search=1,
	__FindPrevious_Search,
	__FindNext_Search,
	__EnterSearchText_Search,
	__EnterReplaceText_Search,
	__FindSelectionBackwards_Search,
	__FindSelectionForward_Search,
	__FindClipboardBackwards_Search,
	__FindClipboardForward_Search,
};

#endif
