// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXTEBase_ReadOnly_enum
#define _H_JXTEBase_ReadOnly_enum

enum {
	__ToggleReadOnlyCmd=1,
};

#endif
