// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXTEBase_CleanWhitespace_enum
#define _H_JXTEBase_CleanWhitespace_enum

enum {
	__ShowWhitespaceCmd=1,
	__CleanAllWhitespaceCmd,
	__CleanWhitespaceSelCmd,
	__CleanAllWSAlignCmd,
	__CleanWSAlignSelCmd,
};

#endif
