// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXTEBase_CheckSpelling
#define _H_JXTEBase_CheckSpelling

static const JUtf8Byte* kCheckSpellingMenuStr =
"* %i CheckAllSpellingCmd::JX"
"|* %i CheckSpellingSelCmd::JX"
;

enum {
	__CheckAllSpellingCmd=1,
	__CheckSpellingSelCmd,
};

#ifndef _H_jx_af_image_jx_jx_spell_check
#define _H_jx_af_image_jx_jx_spell_check
#include <jx-af/image/jx/jx_spell_check.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_spell_check_selection
#define _H_jx_af_image_jx_jx_spell_check_selection
#include <jx-af/image/jx/jx_spell_check_selection.xpm>
#endif

static void ConfigureCheckSpellingMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(__CheckAllSpellingCmd + offset, jx_spell_check);
	menu->SetItemImage(__CheckSpellingSelCmd + offset, jx_spell_check_selection);
};

#endif
