// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_JXTEBase_AdjustMargins_enum
#define _H_JXTEBase_AdjustMargins_enum

enum {
	__CleanRightMarginCmd=1,
	__CoerceRightMarginCmd,
	__ShiftSelLeftCmd,
	__ShiftSelRightCmd,
	__ForceShiftSelLeftCmd,
};

#endif
