name: jx-application-framework
title: JX Application Framework
# core22 build hangs on amd64
# https://forum.snapcraft.io/t/snapcraft-io-build-using-core22-gets-stuck-on-amd64/37363
base: core20
version: "4.1.0"
source-code: https://github.com/jafl/jx_application_framework
issues: https://github.com/jafl/jx_application_framework/issues
contact: https://johnlindal.wixsite.com/aboutme/contact-me
summary: JX is an application framework for use with the X Window System.
description: |
  JX is a full-featured C++ application framework and widget library (SDK) for use with the X Window System.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el

parts:
  jx-application-framework:
    plugin: autotools
    source: .
    override-pull: |
      snapcraftctl pull
      sudo locale-gen en_US.UTF-8
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
    build-environment:
      - LC_ALL: en_US.UTF-8
      - LANG: en_US.UTF-8
    autotools-configure-parameters:
      - release
    stage:
      - include
      - lib
      - bin/compile_jstrings
      - bin/makemake
      - bin/reflex
    build-packages:
      - g++-10
      - make
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
      - libxmu-dev
      - libxi-dev
      - libx11-xcb-dev
      - libxcb-xfixes0-dev
      - libxcb-dri2-0-dev
      - libxpm-dev
      - libjpeg-dev
      - libpng-dev
      - libgd-dev
      - libace-dev
      - libicu-dev
      - libpcre3-dev
      - libxml2-dev
      - libboost-fiber-dev
      - xutils-dev
      - libdrm-dev
      - aspell
      - locales
      - imagemagick
