#!/bin/bash

rm -f  /usr/bin/leibnitz;
rm -rf /usr/lib/leibnitz;
rm -rf /usr/share/doc/leibnitz;
rm -f  `find /usr/share/applications -name 'leibnitz*.desktop'`;
rm -f  `find /usr/share/pixmaps -name 'leibnitz*.xpm'`;
