on:
  workflow_call:
    inputs:
      forge-name:
        type: string
        required: true
      filter:
        type: string
        required: false
        default: "*"
    secrets:
      api-key:
        required: true
      ssh-key:
        required: true

jobs:
  set-defaults:
    name: Mirror to sourceforge
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30
          echo "${{ secrets.ssh-key }}" > ssh-key
          chmod 0600 ssh-key
          R=`curl https://api.github.com/repos/${{ github.repository }}/releases/latest`
          V=`echo $R | jq -r '.tag_name'`; V=${V#v}
          echo "mkdir /home/frs/project/${FORGE_NAME}/v$$V" | sftp  -o StrictHostKeyChecking=no -i ssh-key -b - jafl@frs.sourceforge.net
          for url in `echo $R | jq -r '.assets[].browser_download_url'`; do
            f=${url##*/};
            echo $f;
            if [[ $f == ${{ inputs.filter }} ]]; then
              curl -L -O $url;
              scp -o StrictHostKeyChecking=no -i ssh-key $f jafl@frs.sourceforge.net:/home/frs/project/${{ inputs.forge-name }}/v$V/;
              if [[ $url == *macos* ]]; then
                curl -H "Accept: application/json" -X PUT -d default=mac -d api_key=${{ secrets.api-key }} https://sourceforge.net/projects/${{ inputs.forge-name }}/files/v$V/$f;
              fi;
            fi;
          done
