on:
  workflow_call:
    inputs:
      pkg-name:
        type: string
        required: true
      build-cmd:
        type: string
        required: false
        default: make

jobs:
  build-fedora:
    name: Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install git, glibc-langpack-en for LC_ALL
        run: dnf install -y git glibc-langpack-en

      - name: Set environment variables - after glibc-langpack-en is installed
        run: |
          echo LC_ALL=en_US.utf8 >> $GITHUB_ENV
          echo LANG=en_US.utf8 >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure CI
        run: ./configure ci

      - name: Build
        run: ${{ inputs.build-cmd }}

      - name: Build release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make release
          mv ../${{ inputs.pkg-name }}_* ../${{ inputs.pkg-name }}-* . || true

      - name: Save release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            ${{ inputs.pkg-name }}_*
            ${{ inputs.pkg-name }}-*
