on:
  workflow_call:
    inputs:
      pkg-name:
        type: string
        required: true
      build-cmd:
        type: string
        required: false
        default: make

jobs:
  build-macos:
    name: Build
    runs-on: macos-13
    env:
      PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          curl -LO https://libjx.sourceforge.net/ci/jx-application-framework_darwin.tgz
          tar -xzf jx-application-framework_darwin.tgz
          pushd jx-application-framework-1ci
          ./install /usr/local
          popd
          ./configure ci
          brew install cask
          brew install --cask xquartz

      - name: Build
        run: ${{ inputs.build-cmd }}

      - name: Build release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
          make release
          mv ../${{ inputs.pkg-name }}_* . || true

      - name: Save release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{ inputs.pkg-name }}_*
