on:
  workflow_call:
    inputs:
      pkg-name:
        type: string
        required: true
      forge-name:
        type: string
        required: true
    secrets:
      api-key:
        required: true
      ssh-key:
        required: true
      update-homebrew:
        required: false

jobs:
  upload-release-pkgs:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: release

      - name: Save release packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{ inputs.pkg-name }}?*.*
          file_glob: true

  update-sourceforge:
    name: "-"
    needs: [ upload-release-pkgs ]
    uses: ./.github/workflows/app-mirror-sourceforge.yml
    with:
      forge-name: ${{ inputs.forge-name }}
    secrets:
      api-key: ${{ secrets.api-key }}
      ssh-key: ${{ secrets.ssh-key }}

  publish-version:
    name: Publish version
    runs-on: ubuntu-latest
    needs: [ update-sourceforge ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version & docs
        shell: bash
        run: |
          echo "${{ secrets.ssh-key }}" > ssh-key
          chmod 0600 ssh-key
          f=release/VERSION
          if [[ -d release/doc ]]; then
            f="$f release/doc/*"
          fi
          scp -o StrictHostKeyChecking=no -i ssh-key $f jafl,${{ inputs.forge-name }}@web.sourceforge.net:htdocs/;

  update-homebrew:
    name: Update Homebrew Formulas
    runs-on: ubuntu-latest
    needs: [ upload-release-pkgs ]
    env:
      homebrew_secret: ${{ secrets.update-homebrew }}
    steps:
      - name: Repository Dispatch
        if: ${{ env.homebrew_secret != '' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.update-homebrew }}
          repository: jafl/homebrew-jx
          event-type: new-release
