name: Build
on:
  push:
    branches:
      - utf8
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          ./configure
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          make default test
